### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by Kladdkaka** [GLServers/GLD#64]
- [ ] Configurate Lottery
- [ ] Configurate Bloodmoon
- [x] Get a temporary spawn set up
- [x] Create player market town (disable upkeep or deposit a lot of money via /t deposit)
- [x] Set up community bridge for forums?
- [x] Create player market spawn
- [x] @Kerrus is working on some buildings for the main spawn, we may just use the unfinished version and keep adding onto that as it gets developed.
- [x] We need a mini spawn area for the player market, something simple.
- [x] Finish custom Nexus mechanics plugin
- [x] Unstack water bottles in kit starter, to prevent dupes

**Comment by ryandouglas6** [comment]
Working on the market spawn. Check it off. Should be done by tomorrow.

**Comment by Joannou1** [comment]
Updated todo checklist.

**Comment by ryandouglas6** [comment]
I'll check it out. Mind sending a link to it :p I can't find it
